"""Initial migration.

Revision ID: e76e00f4c79a
Revises: 
Create Date: 2025-02-03 16:00:09.717708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e76e00f4c79a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TB_PY_EMPLOYEE',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('TB_PY_USER',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('createdtime', sa.DateTime(), nullable=False),
    sa.Column('updatedtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('TB_PY_JWT',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('createdtime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['TB_PY_USER.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TB_PY_USER_LOG',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('logintime', sa.DateTime(), nullable=False),
    sa.Column('logouttime', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['TB_PY_USER.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TB_PY_USER_LOG')
    op.drop_table('TB_PY_JWT')
    op.drop_table('TB_PY_USER')
    op.drop_table('TB_PY_EMPLOYEE')
    # ### end Alembic commands ###
